# Generated by Django 4.1.5 on 2023-01-19 13:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=5, primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(db_column='TELEFONO', max_length=15, verbose_name='Teléfono')),
                ('fecha_creado', models.DateTimeField(db_column='FECHA_CREADO', default=datetime.datetime.now, verbose_name='Fecha de creado')),
                ('eliminado', models.BooleanField(db_column='ELIMINADO', default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Tienda',
                'verbose_name_plural': 'Tiendas',
                'db_table': 'TIENDA',
            },
        ),
        migrations.CreateModel(
            name='UsuarioTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(db_column='FECHA_CREADO', default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('eliminado', models.BooleanField(db_column='ELIMINADO', default=False, verbose_name='Eliminado')),
                ('tienda', models.ForeignKey(db_column='TIENDA_ID', on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda', verbose_name='Tienda')),
                ('usuario', models.OneToOneField(db_column='USUARIO', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario de Tienda',
                'verbose_name_plural': 'Usuarios de Tienda',
                'db_table': 'USUARIO_TIENDA',
            },
        ),
    ]
